feat: add alert time limit
afev-org/myddleware pull request #48
Opened 2023-12-13 14:13 UTC by AlexMyddleware

@Myddleware  est-ce que j'ajoute du dynamisme, pour le temps limite par exemple ?

2023-12-13 17:33 UTC, Myddleware commented
Salut @AlexMyddleware en effet le temps limite doit être en paramètre dans la requête. C bien si ce paramètre est dans la table config

2023-12-13 19:28 UTC, Myddleware requested changes
Des petites modifs à faire mais pas grand chose au final, merci.

2023-12-13 19:28 UTC, Myddleware commented on src/Manager/NotificationManager.php
> +            $timeOneHourAgo->modify('-60 minutes');
N'oublie pas d'utiliser la variable dans config ici au lieu du 60 ;)

2023-12-13 19:28 UTC, Myddleware commented on src/Manager/NotificationManager.php
> +            $textMail = 'Alert: the crontab is stopped since more than one hour. Please check the crontab.';
Ici du coup il faut inclure la variable et mettre minutes au lieu de hours

2023-12-13 19:28 UTC, Myddleware commented on src/Manager/NotificationManager.php
> +            $this->sendAlertTaskTooLong();
Très bonne idée de faire des petites fonctions comme cela, bravo ;)

2023-12-14 07:31 UTC, AlexMyddleware commented on src/Manager/NotificationManager.php
> +            $timeOneHourAgo->modify('-60 minutes');
fait 🙂

2023-12-14 07:31 UTC, AlexMyddleware commented on src/Manager/NotificationManager.php
> +            $textMail = 'Alert: the crontab is stopped since more than one hour. Please check the crontab.';
fait 🙂

2023-12-14 07:31 UTC, AlexMyddleware commented on src/Manager/NotificationManager.php
> +            $this->sendAlertTaskTooLong();
merci 🙂

2023-12-14 07:33 UTC, merged